Task 5-6
VladMironchuk/itechart-frontend pull request #1
Opened 2022-01-26 07:30 UTC by VladMironchuk

2022-01-26 10:52 UTC, borodayev requested changes
Please take a look, ask questions if u'll have any.

2022-01-26 10:52 UTC, borodayev commented on src/components/header/header.tsx
> +const Header: React.FC<{ signInHandler: () => void; signUpHandler: () => void }> = ({
Типы лучше выносить в отдельные переменные, инлайн читается тяжело в случае если будет больше пропсов. 

```jsx
type Props = {
  signInHandler: () => void;
  signUpHandler: () => void;
}

...
```

Тоже самое относится и к экстракции пропсов (когда их много).

```jsx
type Props = {
  signInHandler: () => void;
  signUpHandler: () => void;
};

const Header: React.FC<Props> = (props) => {
  const { signInHandler, signUpHandler } = props;
  return (
    <header className="header">
      <h1 className="header__title">Game Store</h1>
      <NavBar signInHandler={signInHandler} signUpHandler={signUpHandler} />
    </header>
  );
};

export default Header;
```

2022-01-26 10:52 UTC, borodayev commented on src/components/layout.tsx
> +  const toggleModal = (param: "in" | "up") => {
Название `param` не несет никакой смысловой нагрузки, необходимо называть переменные так чтобы они смогли дать хотя бы минимальный контекст читателю.

2022-01-26 10:52 UTC, borodayev commented on src/components/layout.tsx
> +  };
В целом, switch case нужно обходить стороной по возможности. Часто такие конструкции нарушают принцип [SRP](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8).

Ничего страшного если создать 2 отдельных хэндлера:

```jsx
const toggleSignInModal = () => setSignInIsVisible((prevState) => !prevState);
const toggleSignUpModal = () => setSignUpIsVisible((prevState) => !prevState);
```

Или даже воткнуть их напрямую (зависит от тимлида и загрузки компонента, некоторые считают такое плохим стилем кода, но нужно знать все методы))):

```jsx
{isSignInVisible && <SignInModal signInHandler={() => setSignInIsVisible((prevState) => !prevState)} />}
{isSignUpVisible && <SignUpModal signUpHandler={() => setSignUpIsVisible((prevState) => !prevState)} />}
```

2022-01-26 10:52 UTC, borodayev commented on src/components/pages/homePage/homePage.tsx
> +// import { useEffect, useState } from "react";
Комменты коммитить неприемлемо, почисти пожалуйста. Если они нужны для будущих разработок, используй git stash

2022-01-26 10:52 UTC, borodayev commented on src/elements/button/button.tsx
> +const FormButton: React.FC<{ url: string; method: string }> = ({ method, url }) => {
Названия компонента и файла должны совпадать

2022-01-26 10:52 UTC, borodayev commented on src/elements/dropdown/dropdown.tsx
> +const Dropdown: React.FC<{ isLogged: boolean; cb: () => void }> = ({ isLogged, cb }) => {
`isLogged` можно достать из контекста? 
Для чего везде пробрасывается `cb`?

2022-01-26 10:52 UTC, borodayev commented on src/elements/dropdown/dropdown.tsx
>      listRef.current?.classList.toggle("hidden");
Почему нельзя отрендерить лист условием в реакте?

2022-01-26 10:52 UTC, borodayev commented on src/elements/dropdown/dropdown.tsx
>    const clickHandler = () => {
Сделай так, чтобы при клике за пределами листа, дропдаун закрывался.

2022-01-26 10:52 UTC, borodayev commented on src/elements/gameCard/gameCard.tsx
>    gamePrice: number;
Пример когда много пропсов и шапка компонента менее читабельна

2022-01-26 10:52 UTC, borodayev commented on src/elements/modal/overlay/overlay.tsx
> +  cb: () => void;
Компонент Modal не должен знать про своих потомков и тем более не должен брать на себя какую-то логику. 
![image](https://user-images.githubusercontent.com/19319629/151148351-dd607b44-d803-4619-b39e-91b598ed0217.png)

Сделай такую иерархию:

- Удали ModalOverlay.
- Оставь Modal компонент, который будет рендерить потомков в портал, установит необходимые стили модалки (сейчас оверлея нет), будет слушать клик за пределами модалки и т.д. Также можно сделать пропсы для title и onClose.

![Screen Shot 2022-01-26 at 16 13 56](https://user-images.githubusercontent.com/19319629/151145149-c98b8b06-f75e-43e3-a370-91420a2763c9.png)

- Затем signInModal и signUpModal внутри будут юзать Modal. <form /> и вся логика должны быть внутри этих компонентов соответственно. Тогда не придется пробрасывать кучу пропсов.

2022-01-26 10:52 UTC, borodayev commented on src/elements/modal/signInModal.tsx
> +    if (!password.match(/.*/)) {
Ошибки должны высвечиваться под инпутами красным текстом. Чтобы не мудрить со стейтами и прочим, очень рекомендую посмотреть в сторону [react-final-form](https://final-form.org/react).

2022-01-26 10:52 UTC, borodayev commented on src/elements/navlink/navlink.tsx
> +        if (cb) {
Для чего cb? Смотрится так что всю эту логику нужно удалить.

2022-01-26 10:52 UTC, borodayev commented on src/elements/searchBar/searchBar.tsx
> +        {!error && !isLoading && (
Если ошибка, то пустой экран?

2022-01-26 10:52 UTC, borodayev commented on src/helpers/useHttp.tsx
Переименуй:
reqConfig => options
applyData => onData

Потом из options лучше экстракнуть переменные на верхнем уровне

2022-01-26 10:52 UTC, borodayev commented on src/helpers/useHttp.tsx
> +    setTimeout(() => setIsLoading(false), 300);
Что если сервер будет отвечать более 300 мс?

2022-01-26 10:52 UTC, borodayev commented on src/helpers/useHttp.tsx
>  import { useCallback, useState } from "react";
папку переименуй в hooks (src/hooks/useHttp)

2022-01-26 10:52 UTC, borodayev commented on webpack.mock.ts
> +  });
![image](https://user-images.githubusercontent.com/19319629/151149078-06ccf8bc-9e4d-4093-a3f4-768df0b1c3f3.png)

С несколькими правками:
- Замокай юзера на сервере (username, password) и проверяй его поля
- При signIn успешный статус код 201. Если неправильные креды то 401, иная ошибка 400
- При signUp нужно юзать тоже POST. success status 200, error 400. Также если все ок, то сохрани юзера хотя бы в памяти.

2022-02-01 07:16 UTC, VladMironchuk commented on src/components/header/header.tsx
> +const Header: React.FC<{ signInHandler: () => void; signUpHandler: () => void }> = ({
Done

2022-02-01 07:35 UTC, VladMironchuk commented on src/components/layout.tsx
> +  const toggleModal = (param: "in" | "up") => {
Done.

2022-02-01 07:35 UTC, VladMironchuk commented on src/components/layout.tsx
> +  };
Done.

2022-02-01 07:35 UTC, VladMironchuk commented on src/components/pages/homePage/homePage.tsx
> +// import { useEffect, useState } from "react";
Done.

2022-02-01 07:35 UTC, VladMironchuk commented on src/elements/button/button.tsx
> +const FormButton: React.FC<{ url: string; method: string }> = ({ method, url }) => {
Done.

2022-02-01 07:38 UTC, VladMironchuk commented on src/elements/dropdown/dropdown.tsx
> +const Dropdown: React.FC<{ isLogged: boolean; cb: () => void }> = ({ isLogged, cb }) => {
Cb я переименовал.
Это триггер, который отображает модалку, если не авторизованный юзер пытается перейти на роуты приватные.

2022-02-01 07:39 UTC, VladMironchuk commented on src/elements/dropdown/dropdown.tsx
>      listRef.current?.classList.toggle("hidden");
Done.

2022-02-01 07:39 UTC, VladMironchuk commented on src/elements/dropdown/dropdown.tsx
>    const clickHandler = () => {
В процессе.

2022-02-01 07:39 UTC, VladMironchuk commented on src/elements/gameCard/gameCard.tsx
>    gamePrice: number;
Change.

2022-02-01 07:40 UTC, VladMironchuk commented on src/elements/modal/overlay/overlay.tsx
> +  cb: () => void;
Done.

2022-02-01 07:41 UTC, VladMironchuk commented on src/elements/modal/signInModal.tsx
> +    if (!password.match(/.*/)) {
Done.

2022-02-01 07:41 UTC, VladMironchuk commented on src/elements/navlink/navlink.tsx
> +        if (cb) {
В процессе.

2022-02-01 07:41 UTC, VladMironchuk commented on src/elements/searchBar/searchBar.tsx
> +        {!error && !isLoading && (
В процессе.

2022-02-01 07:41 UTC, VladMironchuk commented on src/helpers/useHttp.tsx
Done.

2022-02-01 07:42 UTC, VladMironchuk commented on src/helpers/useHttp.tsx
> +    setTimeout(() => setIsLoading(false), 300);
Done.

2022-02-01 07:42 UTC, VladMironchuk commented on src/helpers/useHttp.tsx
>  import { useCallback, useState } from "react";
Done.

2022-02-01 07:43 UTC, VladMironchuk commented on webpack.mock.ts
> +  });
Done.

2022-02-03 17:39 UTC, borodayev approved these changes

2022-02-04 08:20 UTC, merged