Task 7
VladMironchuk/itechart-frontend pull request #2
Opened 2022-02-03 08:57 UTC by VladMironchuk

2022-02-03 17:40 UTC, borodayev commented
@VladMironchuk залей предыдущий пр и обнови ветку плз.

2022-02-03 17:51 UTC, VladMironchuk commented
Хорошо

2022-02-07 06:07 UTC, borodayev requested changes

2022-02-07 06:07 UTC, borodayev commented on src/elements/button/button.tsx
> +type ButtonProps = {
Можно писать просто Props, префикс Button не нужен, т.к компонент дает смысловой контекст

2022-02-07 06:07 UTC, borodayev commented on src/elements/categoryCard/categoryCard.tsx
> +type CategoryCardProps = { cardLogo: string; cardTitle: string };
Same here

2022-02-07 06:07 UTC, borodayev commented on src/elements/dropdown/dropdown.tsx
> +  const [isDropdownVibisble, toggleDropdownVisibility] = useState(false);
Часто встречаются требования называть стейты так (just fyi):

```jsx
const [isDropdownVibisble, setIsDropdownVibisble] = useState(false);
```

2022-02-07 06:07 UTC, borodayev commented on src/elements/dropdown/dropdown.tsx
> +    productsNavLinkRef.current?.classList.toggle("active_title");
С прошлого Пр так и осталось. Почему бы не добавить класс в jsx?

```jsx
const Dropdown: React.FC<DropdownProps> = (props) => {
  const { modalToggler } = props;

  const [isDropdownVibisble, toggleDropdownVisibility] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const onClick = () => {
    toggleDropdownVisibility((prevState) => !prevState);
  };

  useOnClickOutside(dropdownRef, () => {
    toggleDropdownVisibility(() => false);
  });

  return (
    <div ref={dropdownRef} className="dropdown">
      <button
        type="button"
        className={`dropdown__default ${isDropdownVibisble ? "active_title" : ""}`}
        onClick={onClick}
      >
        Products
      </button>
      {isDropdownVibisble && (
        <div className="dropdown__list">
          <ul>
            <Link linkPath="/products/pc" linkText="PC" modalToggler={modalToggler} />
            <Link linkPath="/products/pc" linkText="PS" modalToggler={modalToggler} />
            <Link linkPath="/products/pc" linkText="XBox" modalToggler={modalToggler} />
          </ul>
        </div>
      )}
    </div>
  );
};

export default Dropdown;
```

2022-02-07 06:07 UTC, borodayev commented on src/elements/dropdown/dropdown.tsx
>    const clickHandler = () => {
clickHandler => onClick

2022-02-07 06:07 UTC, borodayev commented on src/elements/dropdown/dropdown.tsx
> +            <Link linkPath="/products/pc" linkText="PS" modalToggler={modalToggler} />
Аккуратно копи паст))) /products/pc

2022-02-07 06:07 UTC, borodayev commented on src/elements/formInput/formInput.tsx
> +      <input onChange={changeHandler} value={inputValue} type="text" name={label} />
onChange?

2022-02-07 06:07 UTC, borodayev commented on src/elements/gameCard/gameCard.tsx
> +export type GameCardContent = {
Props?

2022-02-07 06:07 UTC, borodayev commented on src/elements/modal/overlay/overlay.tsx
> +const Modal: React.FC<ModalProps> = (props) => {
Название файла и компонента не соответствует. Писал похожий коммент в прошлом пр, пройдись по всем файлам и проверь еще раз пожалуйста

2022-02-07 06:07 UTC, borodayev commented on src/components/layout.tsx
> +  const toggleSignInModal = () => {
Насколько я помню ты собирался перенести это в редакс?

2022-02-07 06:13 UTC, borodayev commented
+ в некоторых файлах есть ошибки ts 
![image](https://user-images.githubusercontent.com/19319629/152734095-b1c21eb9-c6e4-4ca3-a668-27a4192f47b2.png)

2022-02-07 06:21 UTC, borodayev commented on package.json
> +    "react-final-form": "^6.5.7",
Если не будешь использовать, удали из зависимостей

2022-02-11 07:28 UTC, borodayev approved these changes
👍

2022-02-14 09:17 UTC, merged