Task 10
VladMironchuk/itechart-frontend pull request #4
Opened 2022-02-22 06:59 UTC by VladMironchuk

2022-02-22 14:22 UTC, borodayev requested changes

2022-02-22 14:22 UTC, borodayev commented on src/components/pages/productsPage/filterSidebar.tsx
> +const FilterSidebar: React.FC<Props> = (props) => {
Компонент кажется перегруженным, разбей на более мелкие компоненты (например фильтры отдельно, сортировка отдельно). + если есть стейт менеджмент, лучше юзать его механизмы, чем пробрасывать все пропсы вниз.

2022-02-22 14:22 UTC, borodayev commented on src/components/pages/productsPage/games.tsx
> +          games.map(({ rating, gameLogo, gameTitle, gamePrice, gamePlatforms, ageLimit, gameDescription }) => (
Можно передать 1 пропс game, не доставая внутренности на верхнем уровне.

<GameCard game={game} />

2022-02-22 14:22 UTC, borodayev commented on src/components/pages/homePage/homePage.tsx
> +      <SearchBar placeholder="Search" />
Поиск не работает нигде

2022-02-22 14:22 UTC, borodayev commented on src/components/pages/productsPage/productsPage.tsx
> +        <Suspense
Это пробовал сделать?

![image](https://user-images.githubusercontent.com/19319629/155148299-2b038813-6267-4003-8e58-7f91f783501e.png)

2022-02-22 14:22 UTC, borodayev commented on src/elements/navlink/link.tsx
> +import { useSelector } from "react-redux";
Этот компонент излишен, мы же реализовали логику с #login

2022-02-22 14:22 UTC, borodayev commented on src/elements/searchBar/searchBar.tsx
>          className="search-bar"
Этот код должен быть просто в хендлере onChange, сделай еще debounce запроса (можно сделать как кастом хук).

```jsx
  useEffect(() => {
    if (inputValue === "") {
      return;
    }
    (async () => {
      const initGames = await get(`/api/search/${inputValue}`);
      if (response.ok) {
        setGames(initGames);
      }
    })();
  }, [inputValue]);
```

2022-02-22 14:26 UTC, borodayev commented
@VladMironchuk поправь стили ссылок и фильтров:

![image](https://user-images.githubusercontent.com/19319629/155151778-7a7b414a-99f8-4554-9910-f3a569afbf88.png)

![image](https://user-images.githubusercontent.com/19319629/155152027-e3dde0d2-b0be-4324-bfc5-440e8171ea7a.png)

2022-02-22 19:28 UTC, VladMironchuk commented on src/elements/navlink/link.tsx
> +import { useSelector } from "react-redux";
Странно, не подтянулся коммит с мастера

2022-02-22 19:28 UTC, VladMironchuk commented on src/elements/navlink/link.tsx
> +import { useSelector } from "react-redux";
Upd: Пофиксил

2022-02-22 20:17 UTC, VladMironchuk commented on src/components/pages/productsPage/productsPage.tsx
> +        <Suspense
нет, я не совсем понимаю, как его написать

2022-02-23 06:48 UTC, borodayev requested changes

2022-02-23 06:48 UTC, borodayev commented on src/components/pages/homePage/homePage.tsx
> +  const [{ games }, setGames] = useState<{ games: GameCardContent["game"][] }>({ games: [] });
А зачем тут оборачивать в объект?

2022-02-23 06:48 UTC, borodayev commented on src/components/pages/productsPage/filterSidebar.tsx
> +const FilterCriteria: React.FC<FilterCriteriaProps> = (props) => {
В одном файле должен быть только один компонент

2022-02-23 07:09 UTC, merged